name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run compile
      - run: npx vsce package
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: '*.vsix'
      - name: Publish to Open VSX
        if: env.OVSX_TOKEN != ''
        run: npm run publish:ovsx
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
      - name: Publish to VS Code Marketplace
        if: env.VSCE_PAT != ''
        run: npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
